import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('language switch keeps its reusable children wrapper while using Dropdown', async () => {
    const [component, style, entry, readme, showcasePage, showcaseStyle] = await Promise.all([
        readFile('src/components/LanguageSwitch/LanguageSwitch.tsx', 'utf8'),
        readFile('src/components/LanguageSwitch/LanguageSwitch.scss', 'utf8'),
        readFile('src/components/LanguageSwitch/index.ts', 'utf8'),
        readFile('src/components/LanguageSwitch/README.md', 'utf8'),
        readFile('src/showcase/components/language-switch/LanguageSwitchShowcasePage.tsx', 'utf8'),
        readFile('src/showcase/components/language-switch/LanguageSwitchShowcasePage.scss', 'utf8'),
    ])

    assert.match(component, /children\?:\s*ReactNode/)
    assert.match(component, /import \{ Icon \} from '@\/components\/Icon'/)
    assert.match(component, /APP_CONFIG\.enableI18n/)
    assert.match(component, /style=\{\{ display: 'none' \}\}/)
    assert.match(component, /function LanguageSwitchContent/)
    assert.match(component, /useState\(false\)/)
    assert.match(component, /import \{[\s\S]*Dropdown/)
    assert.doesNotMatch(component, /import \{ Picker/)
    assert.doesNotMatch(component, /useTranslation/)
    assert.doesNotMatch(component, /useRef/)
    assert.match(component, /APP_LANGUAGES/)
    assert.match(component, /LANGUAGE_DROPDOWN_OPTIONS/)
    assert.match(component, /changeAppLanguage/)
    assert.match(component, /useAppStore/)
    assert.match(component, /function renderLanguageTrigger/)
    assert.match(component, /type DropdownTriggerRenderProps/)
    assert.match(component, /event\.currentTarget\.click\(\)/)
    assert.match(component, /function handleDropdownOpenChange/)
    assert.match(component, /onOpen\?\.\(\)/)
    assert.match(component, /async function handleLanguageChange/)
    assert.match(component, /isChangingLanguage \|\| nextLanguageCode === languageCode/)
    assert.match(component, /<Dropdown/)
    assert.match(component, /options=\{LANGUAGE_DROPDOWN_OPTIONS\}/)
    assert.match(component, /value=\{languageCode\}/)
    assert.match(component, /showIcon=\{false\}/)
    assert.match(component, /disabled=\{isChangingLanguage\}/)
    assert.match(component, /maskClassName="language-switch__mask"/)
    assert.match(component, /renderTrigger=\{renderLanguageTrigger\}/)
    assert.match(component, /onOpenChange=\{handleDropdownOpenChange\}/)
    assert.match(component, /window\.location\.reload\(\)/)
    assert.match(component, /const triggerContent = children === undefined \?/)
    assert.match(component, /language-switch__default/)
    assert.match(component, /<Icon name="language"/)
    assert.doesNotMatch(component, /<Icon name="arrow-down"/)
    assert.match(component, /\{triggerContent\}/)
    assert.match(entry, /export \{ LanguageSwitch \} from '\.\/LanguageSwitch\.tsx'/)
    assert.match(readme, /children/)
    assert.doesNotMatch(readme, /Vue|slot/)
    assert.match(readme, /Default icon trigger/)
    assert.match(readme, /Custom button trigger/)
    assert.match(readme, /Dropdown/)
    assert.match(readme, /APP_LANGUAGES/)
    assert.match(readme, /简体中文、繁體中文、日本語、한국어和 English/)
    assert.match(readme, /透明且无模糊的遮罩/)
    assert.match(readme, /page reloads/)
    assert.match(showcasePage, /export function LanguageSwitchShowcasePage/)
    assert.match(showcasePage, /useAppStore/)
    assert.match(showcasePage, /<SecondaryHeader title="语言切换" \/>/)
    assert.doesNotMatch(showcasePage, /Vue|slot/)
    assert.doesNotMatch(showcasePage, /useState/)
    assert.doesNotMatch(showcasePage, /打开次数/)
    assert.doesNotMatch(showcasePage, /onOpen/)
    assert.match(showcasePage, /<LanguageSwitch \/>/)
    assert.match(showcasePage, /<LanguageSwitch>/)
    assert.match(showcasePage, /默认图标入口/)
    assert.match(showcasePage, /自定义按钮入口/)
    assert.match(showcasePage, /多语言下拉菜单/)
    assert.match(showcasePage, /切换语言/)
    assert.match(showcasePage, /className="full-btn mt-30"/)
    assert.match(showcasePage, /className="flex items-center mt-30"/)
    assert.doesNotMatch(showcaseStyle, /&-icon-row/)
    assert.doesNotMatch(showcaseStyle, /&-trigger/)
    assert.match(showcaseStyle, /\.language-switch-showcase\s*\{/)
    assert.match(style, /&__mask\s*\{[\s\S]*background:\s*transparent;/)
    assert.match(style, /backdrop-filter:\s*none;/)
    assert.match(style, /-webkit-backdrop-filter:\s*none;/)
})
